server:
  port: 6003
  servlet:
    context-path: /
spring:
  application:
    name: security-cas-example
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
######################################################### thymeleaf 配置
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8
######################################################### datasource 配置
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.61.40.18:3705/hk_pms?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: pms
    password: pmsadmin
######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL

######################################################### security 配置
hk:
  authentication:
    cas:
      key: xxxxxx
      cas-login-url: http://127.0.0.1:8888/cas/login
      send-renew: false
      cas-server-url-prefix: http://192.168.1.76:8888/cas
      service: http://127.0.0.1:${server.port}/login/cas
      ticket-validator-url: http://127.0.0.1:8888/cas
      cas-server-logout-url: http://127.0.0.1:8888/cas/logout
    login:
      logout-url: /logout
#hk:
#  authentication:
#    login:
#      login-url: /login
#      login-processing-url: /login
#      logout-url: /logout
#      logout-success-url: ${server.servlet.context-path}
#      username-parameter: username
#      password-parameter: password
#      maximum-sessions: 2
######################################################### log 配置
logging:
  config: classpath:log4j2.xml
