server:
  port: 8082
spring:
  main:
    banner-mode: "off"
  application:
    name: nacos-discovery-example
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 182.61.40.18:8848
logging:
  config: "classpath:log4j2.xml"