server:
  port: 80
  context-path: /
  
spring:
################################################################### thymeleaf
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html; charset=utf-8

logging: 
  config: classpath:log4j2.xml   #日志文件配置路径
  
  
fs: 
  upload:  
    basepath: D:/qianduan
