server:
  port: 6001
  servlet:
    context-path: /
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.61.40.18:3705/hk_pms?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: pms
    password: pmsadmin
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      filter:
        stat:
          slow-sql-millis: 5000
      connection-properties: druid.stat.mergeSql=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        allow: 127.0.0.1
        login-username: druidAdmin
        login-password: druidAdmin@%*
      web-stat-filter:
        enabled: true
        url-pattern: /**
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
######################################################### thymeleaf 配置
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8
######################################################### shiro 配置
shiro:
  enable: true
  loginUrl: '/login'
  successUrl: '/'
  sessionManager:
    sessionIdUrlRewritingEnabled: false

######################################################### log 配置
logging:
  config: classpath:log4j2.xml