server:
  port: 6001
  servlet:
    context-path: /
spring:
  application:
    name: shiro-example
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/hk_pms?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: pms
    password: pmsadmin
######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL
######################################################### thymeleaf 配置
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8
########################################################## shiro 配置
shiro:
  enabled: true
  annotations:
    enable: true
  loginUrl: "/login"
  successUrl: ${server.servlet.context-path}
  userNativeSessionManager: false
  unauthorizedUrl: "/unauthorized"
  sessionManager:
    deleteInvalidSessions: true
    sessionIdUrlRewritingEnabled: false
  filter-chain-definition:
    anon:
     - "/favicon.ico"
     - "/resources/**"
     - ${shiro.unauthorizedUrl}
    authc:
      - "/**"
    logout:
      - "/logout"
######################################################### log 配置
logging:
  config: classpath:log4j2.xml
