server:
  port: 7771

spring:
  application:
    name: hk-kafka-spring-cloud-stream-consumer01
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  cloud:
########################################################################### spring cloud stream 配置
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - sjq-01:9092
            - sjq-02:9092
            - sjq-03:9092
      bindings:
        input:
          destination: test-destination
          group: group2
