server:
  port: 7771

spring:
  application:
    name: hk-stream-consumner01
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  cloud:
    ########################################################################### spring cloud stream 配置
    stream:
      default-binder: kafka
      instance-index: 0
      instance-count: 3
      kafka:
        binder:
          brokers:
            - sjq-01:9092
            - sjq-02:9092
            - sjq-03:9092
          # 最小分区数
          min-partition-count: 2
          # 分区副本数
          replication-factor: 2
          # 消息确认ack ,默认为 1 ,可以设置为 'all'
          required-acks: "1"
          # 允许自动创建 topic
          auto-create-topics: true
      bindings:
        input:
          # 消息接收的主题，见生产者 （hk-sso-server） 配置文件中的 spring.cloud.stream.bindings.output.destination 参数值
          destination: destination-01
          # 组名，如果不指定组名，会生成一个匿名组名，在kafka中，不同组的实例都会消费生产者发送的消息
          group: group2
