server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: hk-oracle-example
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
         dialect: org.hibernate.dialect.Oracle10gDialect
################################################################### datasource
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:127.0.0.1:1521:orcl
    username: card12345
    password: card12345
######################################################### hikari datasource 配置
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL





