server:
  port: 6005
  servlet:
    context-path: /

spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: hk-elasticsearch-example
  data:
    elasticsearch:
      #     名称：要和 $elasticsearch_home}/config/elasticsearch.yml 中的 cluster.name 参数一样
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.50:9300,192.168.1.51:9300,192.168.1.90:9300
  elasticsearch:
    rest:
      uris:
        - 192.168.1.50:9200
        - 192.168.1.51:9200
        - 192.168.1.90:9200
logging:
  level:
    root: error
    com.hk: info