server:
  port: 6005
  servlet:
    context-path: /
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: hk-elasticsearch-example
  data:
    elasticsearch:
      #     名称：要和 $elasticsearch_home}/config/elasticsearch.yml 中的 cluster.name 参数一样
      cluster-name: docker-cluster
      cluster-nodes: 192.168.117.100:9300,192.168.117.101:9300,192.168.117.102:9300
  #      cluster-nodes: 182.61.40.18:9300
  elasticsearch:
    rest:
      uris:
        - 192.168.117.100:9200
        - 192.168.117.101:9200
        - 192.168.117.102:9200
logging:
  level:
    root: error
    com.hk: info
    org.springframework.data.elasticsearch: debug