// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hk.proto.grpc;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hk.proto.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 2;</code>
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
