// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hk.proto.grpc;

public interface UserResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hk.proto.UserResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  java.util.List<com.hk.proto.grpc.UserResponse> 
      getUserResponseList();
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  com.hk.proto.grpc.UserResponse getUserResponse(int index);
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  int getUserResponseCount();
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  java.util.List<? extends com.hk.proto.grpc.UserResponseOrBuilder> 
      getUserResponseOrBuilderList();
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  com.hk.proto.grpc.UserResponseOrBuilder getUserResponseOrBuilder(
      int index);
}
