// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hk.proto.grpc;

/**
 * Protobuf type {@code com.hk.proto.UserResponseList}
 */
public  final class UserResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hk.proto.UserResponseList)
    UserResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserResponseList.newBuilder() to construct.
  private UserResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserResponseList() {
    userResponse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              userResponse_ = new java.util.ArrayList<com.hk.proto.grpc.UserResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            userResponse_.add(
                input.readMessage(com.hk.proto.grpc.UserResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        userResponse_ = java.util.Collections.unmodifiableList(userResponse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hk.proto.grpc.StudentProto.internal_static_com_hk_proto_UserResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hk.proto.grpc.StudentProto.internal_static_com_hk_proto_UserResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hk.proto.grpc.UserResponseList.class, com.hk.proto.grpc.UserResponseList.Builder.class);
  }

  public static final int USERRESPONSE_FIELD_NUMBER = 1;
  private java.util.List<com.hk.proto.grpc.UserResponse> userResponse_;
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  public java.util.List<com.hk.proto.grpc.UserResponse> getUserResponseList() {
    return userResponse_;
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  public java.util.List<? extends com.hk.proto.grpc.UserResponseOrBuilder> 
      getUserResponseOrBuilderList() {
    return userResponse_;
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  public int getUserResponseCount() {
    return userResponse_.size();
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  public com.hk.proto.grpc.UserResponse getUserResponse(int index) {
    return userResponse_.get(index);
  }
  /**
   * <pre>
   * 集合
   * </pre>
   *
   * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
   */
  public com.hk.proto.grpc.UserResponseOrBuilder getUserResponseOrBuilder(
      int index) {
    return userResponse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userResponse_.size(); i++) {
      output.writeMessage(1, userResponse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userResponse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userResponse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hk.proto.grpc.UserResponseList)) {
      return super.equals(obj);
    }
    com.hk.proto.grpc.UserResponseList other = (com.hk.proto.grpc.UserResponseList) obj;

    boolean result = true;
    result = result && getUserResponseList()
        .equals(other.getUserResponseList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserResponseCount() > 0) {
      hash = (37 * hash) + USERRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getUserResponseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hk.proto.grpc.UserResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hk.proto.grpc.UserResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hk.proto.grpc.UserResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hk.proto.grpc.UserResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hk.proto.grpc.UserResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hk.proto.UserResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hk.proto.UserResponseList)
      com.hk.proto.grpc.UserResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hk.proto.grpc.StudentProto.internal_static_com_hk_proto_UserResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hk.proto.grpc.StudentProto.internal_static_com_hk_proto_UserResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hk.proto.grpc.UserResponseList.class, com.hk.proto.grpc.UserResponseList.Builder.class);
    }

    // Construct using com.hk.proto.grpc.UserResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserResponseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (userResponseBuilder_ == null) {
        userResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userResponseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hk.proto.grpc.StudentProto.internal_static_com_hk_proto_UserResponseList_descriptor;
    }

    @java.lang.Override
    public com.hk.proto.grpc.UserResponseList getDefaultInstanceForType() {
      return com.hk.proto.grpc.UserResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.hk.proto.grpc.UserResponseList build() {
      com.hk.proto.grpc.UserResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hk.proto.grpc.UserResponseList buildPartial() {
      com.hk.proto.grpc.UserResponseList result = new com.hk.proto.grpc.UserResponseList(this);
      int from_bitField0_ = bitField0_;
      if (userResponseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userResponse_ = java.util.Collections.unmodifiableList(userResponse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userResponse_ = userResponse_;
      } else {
        result.userResponse_ = userResponseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hk.proto.grpc.UserResponseList) {
        return mergeFrom((com.hk.proto.grpc.UserResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hk.proto.grpc.UserResponseList other) {
      if (other == com.hk.proto.grpc.UserResponseList.getDefaultInstance()) return this;
      if (userResponseBuilder_ == null) {
        if (!other.userResponse_.isEmpty()) {
          if (userResponse_.isEmpty()) {
            userResponse_ = other.userResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserResponseIsMutable();
            userResponse_.addAll(other.userResponse_);
          }
          onChanged();
        }
      } else {
        if (!other.userResponse_.isEmpty()) {
          if (userResponseBuilder_.isEmpty()) {
            userResponseBuilder_.dispose();
            userResponseBuilder_ = null;
            userResponse_ = other.userResponse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userResponseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUserResponseFieldBuilder() : null;
          } else {
            userResponseBuilder_.addAllMessages(other.userResponse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hk.proto.grpc.UserResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hk.proto.grpc.UserResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hk.proto.grpc.UserResponse> userResponse_ =
      java.util.Collections.emptyList();
    private void ensureUserResponseIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        userResponse_ = new java.util.ArrayList<com.hk.proto.grpc.UserResponse>(userResponse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hk.proto.grpc.UserResponse, com.hk.proto.grpc.UserResponse.Builder, com.hk.proto.grpc.UserResponseOrBuilder> userResponseBuilder_;

    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public java.util.List<com.hk.proto.grpc.UserResponse> getUserResponseList() {
      if (userResponseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userResponse_);
      } else {
        return userResponseBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public int getUserResponseCount() {
      if (userResponseBuilder_ == null) {
        return userResponse_.size();
      } else {
        return userResponseBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public com.hk.proto.grpc.UserResponse getUserResponse(int index) {
      if (userResponseBuilder_ == null) {
        return userResponse_.get(index);
      } else {
        return userResponseBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder setUserResponse(
        int index, com.hk.proto.grpc.UserResponse value) {
      if (userResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserResponseIsMutable();
        userResponse_.set(index, value);
        onChanged();
      } else {
        userResponseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder setUserResponse(
        int index, com.hk.proto.grpc.UserResponse.Builder builderForValue) {
      if (userResponseBuilder_ == null) {
        ensureUserResponseIsMutable();
        userResponse_.set(index, builderForValue.build());
        onChanged();
      } else {
        userResponseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder addUserResponse(com.hk.proto.grpc.UserResponse value) {
      if (userResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserResponseIsMutable();
        userResponse_.add(value);
        onChanged();
      } else {
        userResponseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder addUserResponse(
        int index, com.hk.proto.grpc.UserResponse value) {
      if (userResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserResponseIsMutable();
        userResponse_.add(index, value);
        onChanged();
      } else {
        userResponseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder addUserResponse(
        com.hk.proto.grpc.UserResponse.Builder builderForValue) {
      if (userResponseBuilder_ == null) {
        ensureUserResponseIsMutable();
        userResponse_.add(builderForValue.build());
        onChanged();
      } else {
        userResponseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder addUserResponse(
        int index, com.hk.proto.grpc.UserResponse.Builder builderForValue) {
      if (userResponseBuilder_ == null) {
        ensureUserResponseIsMutable();
        userResponse_.add(index, builderForValue.build());
        onChanged();
      } else {
        userResponseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder addAllUserResponse(
        java.lang.Iterable<? extends com.hk.proto.grpc.UserResponse> values) {
      if (userResponseBuilder_ == null) {
        ensureUserResponseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userResponse_);
        onChanged();
      } else {
        userResponseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder clearUserResponse() {
      if (userResponseBuilder_ == null) {
        userResponse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public Builder removeUserResponse(int index) {
      if (userResponseBuilder_ == null) {
        ensureUserResponseIsMutable();
        userResponse_.remove(index);
        onChanged();
      } else {
        userResponseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public com.hk.proto.grpc.UserResponse.Builder getUserResponseBuilder(
        int index) {
      return getUserResponseFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public com.hk.proto.grpc.UserResponseOrBuilder getUserResponseOrBuilder(
        int index) {
      if (userResponseBuilder_ == null) {
        return userResponse_.get(index);  } else {
        return userResponseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public java.util.List<? extends com.hk.proto.grpc.UserResponseOrBuilder> 
         getUserResponseOrBuilderList() {
      if (userResponseBuilder_ != null) {
        return userResponseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userResponse_);
      }
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public com.hk.proto.grpc.UserResponse.Builder addUserResponseBuilder() {
      return getUserResponseFieldBuilder().addBuilder(
          com.hk.proto.grpc.UserResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public com.hk.proto.grpc.UserResponse.Builder addUserResponseBuilder(
        int index) {
      return getUserResponseFieldBuilder().addBuilder(
          index, com.hk.proto.grpc.UserResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * 集合
     * </pre>
     *
     * <code>repeated .com.hk.proto.UserResponse userResponse = 1;</code>
     */
    public java.util.List<com.hk.proto.grpc.UserResponse.Builder> 
         getUserResponseBuilderList() {
      return getUserResponseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.hk.proto.grpc.UserResponse, com.hk.proto.grpc.UserResponse.Builder, com.hk.proto.grpc.UserResponseOrBuilder> 
        getUserResponseFieldBuilder() {
      if (userResponseBuilder_ == null) {
        userResponseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.hk.proto.grpc.UserResponse, com.hk.proto.grpc.UserResponse.Builder, com.hk.proto.grpc.UserResponseOrBuilder>(
                userResponse_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        userResponse_ = null;
      }
      return userResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hk.proto.UserResponseList)
  }

  // @@protoc_insertion_point(class_scope:com.hk.proto.UserResponseList)
  private static final com.hk.proto.grpc.UserResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hk.proto.grpc.UserResponseList();
  }

  public static com.hk.proto.grpc.UserResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserResponseList>
      PARSER = new com.google.protobuf.AbstractParser<UserResponseList>() {
    @java.lang.Override
    public UserResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hk.proto.grpc.UserResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

