// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hk.proto.grpc;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hk.proto.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>string phone = 3;</code>
   */
  java.lang.String getPhone();
  /**
   * <code>string phone = 3;</code>
   */
  com.google.protobuf.ByteString
      getPhoneBytes();
}
