// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hk.proto.grpc;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hk.proto.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
