server:
  port: 80
  context-path: /
spring:
  #国际化配置
  #encoding:文件编码
  #basename: 注意:这里不需要写 classpath: 前缀，也不需要写 .properties后缀，多个文件使用英文逗号(,)分隔
  #       自定义的需要写在spring定义的前面，否则有相同的key可能会覆盖
  messages: 
    encoding: UTF-8
    basename: org/springframework/security/messages_zh_CN  
    
  thymeleaf: 
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html; charset=utf-8
  jpa: 
    show-sql: true
    generate-ddl: false
    properties:
      hibernate: 
         dialect: org.hibernate.dialect.MySQL57InnoDBDialect
################################################################### datasource
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.76:3306/hk_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root
################################################################### druid
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-on-borrow: true
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter-class-names:
      - stat
      - wall
      - log4j2
#      connect-properties: 
#        druid.stat.mergeSql: true
#        druid.stat.slowSqlMillis: 5000
  
logging:
  config: classpath:log4j2.xml
  
wechat: 
  mp: 
    appId: wx72303d4d8b1f0d00
    secret: 19175e5d7111969a1dcc86048d338f86


# 微信二维码参数配置    
wx: 
  qrcode:
    call-host: http://cef00c48.ngrok.io
    callback-url: /wechat/callback
  
    
    
    
    