server:
  port: 80
  context-path: /

spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html; charset=utf-8

logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG
wechat:
  mp:
    appId: wxeb90fbc4967a11b1
    secret: 7fbd0b68cf003238306745446bf0bf16
    token: hk9060
    aesKey: null