server:
  port: 8080
  servlet:
    context-path: /
############################ spring configuration ##############################
spring:
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      enabled: false # 禁用文件上传功能
  autoconfigure:
    exclude:
    # 默认情况下，spring boot web 应用会装配一些功能组件 bean,大多数情况下，可以选择性关闭自动装配的组件bean,以提升性能。
      - org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration
      - org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
    formcontent:
      filter:
        enabled: false
######################################################### 国际化配置
  messages:
    encoding: UTF-8
    basename: org/springframework/security/messages,com/hk/core/i18n/messages,messages
    cache-duration: -1ms
######################################################### thymeleaf 配置
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html; charset=utf-8
######################################################### datasource 配置
  datasource:
    name: hikari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://182.61.40.18:3705/hk_emi?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://192.168.1.244:3306/sjq_ygpj_2019?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    url: jdbc:mysql://192.168.1.244:3306/sjq_ygpj_2019?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
#    password: sjq123&*(
    password: root
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
      minimum-idle: 10
      connection-timeout: 30000
      read-only: false
      connection-test-query: SELECT 1 FROM DUAL
################################################################### redis
  cache:
    type: redis
  redis:
    host: 12.0.0.1
    password:
    port: 6379
    database: 2
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: -1ms

######################################################### logging 配置
logging:
  level:
    root: error
    com.hk: info
    org.springframework.web.socket: debug
    org.apache.kafka: debug
#    org.springframework.security: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: debug
