spring:
  application:
    name: rabbitmq-example
    
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true