server:
  port: 80
  context-path: /

spring:
  application:
    name: rabbitmq-example
  thymeleaf: 
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html; charset=utf-8
    
  rabbitmq:
    host: 192.168.64.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true
    

amqp: 
  example:
    fanout:
      exchange: amqp.example.fanout.exchange