server:
  port: 6130
spring:
  main:
    banner-mode: 'off'
  cache:
    type: redis
  redis:
    cluster:
#     获取失败最大重定向次数
      max-redirects: 2
#      集群节点配置
      nodes:
        - "192.168.64.128:6379"
        - "192.168.64.129:6379"
        - "192.168.64.130:6379"
    timeout: 2000ms
#    password:
    lettuce:
      pool:
#       连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
#       连接池中的最小空闲连接
        min-idle: 5
#       连接池中的最大空闲连接
        max-idle: 10
#       连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
logging:
  level:
    root: error
    com.hk: debug
