server:
  port: 6130
spring:
  main:
    banner-mode: 'off'
  cache:
    type: redis
  redis:
#  redis 单节点
    host: 192.168.64.128
    password:
    port: 6350
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
#       连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
#       连接池中的最小空闲连接
        min-idle: 5
#       连接池中的最大空闲连接
        max-idle: 10
#       连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
logging:
  level:
    root: error
    com.hk: debug
