server:
  port: 6610
  servlet:
    context-path: /
spring:
  application:
    name: hk-stream-consumner01
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 182.61.40.18
    username: test
    password: test
    virtual-host: /test
  cloud:
########################################################################### spring cloud stream 配置
    stream:
      default-binder: rabbit
      bindings:
      # rabbitmq 指定队列名称，如果不指定 group，会随机生成，队列名是 以 bindings 的 mapKey + . + group 值组成，如这里是 input.group
        publish_input:
          # rabbitmq 中指定交换机名称
          destination: publish_stream
          group: publish01
        routekey_input:
          destination: routekey_stream
          group: routekey01
        topic_input:
          destination: topic_stream
          group: topic01
        delayed_input:
          destination: delayed_stream
      rabbit:
        bindings:
          publish_input:
            consumer:
              exchange-type: fanout
          routekey_input:
            consumer:
              # 配置 routeKey
              binding-routing-key: "key1"
              exchange-type: direct
          topic_input:
            consumer:
#            使用通配符的 routeKey , * 只能单机级匹配
              binding-routing-key: "topicKey1.*"
#              指定类型，默认就是 topic
              exchange-type: topic
          delayed_input:
            consumer:
              delayed-exchange: true