server:
  port: 6611
  servlet:
    context-path: /
spring:
  application:
    name: hk-stream-consumner02
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 182.61.40.18
    username: guest
    password: guest#root
    virtual-host: /
  cloud:
########################################################################### spring cloud stream 配置
    stream:
      default-binder: rabbit
      bindings:
        input:
          destination: output
#
#      bindings:
#        input:
#          # 消息接收的主题，见生产者 （hk-sso-server） 配置文件中的 spring.cloud.stream.bindings.output.destination 参数值
#          destination: destination-01
#          # 组名，如果不指定组名，会生成一个匿名组名，在kafka中，不同组的实例都会消费生产者发送的消息
#          group: group2