server:
  port: 8082
  servlet:
    context-path: /
spring:
  main:
    banner-mode: 'off'
  application:
    name: rocketmq-sprongcloud-stream-consumer02
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 119.23.31.32:9876
          #          是否为 Producer 和 Consumer 开启消息轨迹功能，默认为 true
          enable-msg-trace: true
          #          消息轨迹开启后存储的 topic 名称
          customized-trace-topic: RMQ_SYS_TRACE_TOPIC
        #           阿里云 账号 accessKey
        #          access-key:
        #          阿里云账号 secretKey
        #          secret-key:
        bindings:
          tag-stream-input:
            consumer:
              #  消费指定 Tag的消息
              tags: "TagB"
      bindings:
        tag-stream-input:
          destination: tag-stream-topic
          group: tag-stream-consumer-group02


